spring:
    application:
        name: netty-start

server:
    host: localhost
    port: 9000
    netty:
        boss-count: 1
        worker-count: 4
        keep-alive: true
        backlog: 128

network:
    protocol:
        magic: 0x3D3D
